## Creating vectors and matrix

In [1]:
import numpy as np

In [2]:
#Create a vector as a row
vector_row=np.array([1,2,3])

In [3]:
# Create a vector as a column
vector_column=np.array([[1],
                       [2],
                       [3]])

In [4]:
# Create a matrix
matrix=np.array([[1,2],
                [1,2],
                [1,2]])

In [5]:
# Numpy matrix data structure
matrix_obj= np.mat([[1,2],
                   [1,2],
                   [1,2]])
print(matrix_obj)

[[1 2]
 [1 2]
 [1 2]]


In [6]:
import numpy as np
from scipy import sparse

In [7]:
# create matrix
matrix=np.array([[0,0],
                [0,2],
                [3,0]])

In [8]:
# create compressed sparse row (CSR) matrix
# Sparse matrices only store nonzero elements and assume all other values to be zero.
matrix_sparse=sparse.csr_matrix(matrix)

In [9]:
#view sparse matrix
print(matrix_sparse)

  (1, 1)	2
  (2, 0)	3


In [10]:
#create large matrix
matrix_large=np.array([[0,0,0,0,0,0,0,0,0,0,],
                      [0,1,0,0,0,0,0,0,0,0],
                      [3,0,0,0,0,0,0,0,0,0]])

In [11]:
# create compressed sparse row (CSR) 
matrix_large_sparse=sparse.csr_matrix(matrix_large)

In [12]:
#view original sparce matrix
print(matrix_sparse)

  (1, 1)	2
  (2, 0)	3


In [13]:
#view large sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


## Selecting Elements in a vector or matrix

In [14]:
import numpy as np
#create row vector
vector=np.array([1,2,3,4,5,6])

In [15]:
#create matrix
matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [16]:
#select fifth element of vector
vector[5]

6

In [17]:
#select third row, third column
matrix[2,2]

9

In [18]:
#selecting all elements of vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [19]:
#selecting everything up and including 3rd element
vector[:3]

array([1, 2, 3])

In [20]:
#selecting everything after the 3rd element
vector[3:]

array([4, 5, 6])

In [21]:
# selecting the last element
vector[-1]

6

In [22]:
# selecting the first 2 rows and all columns in matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

## Describing a matrix

In [23]:
#View number of rows and columns
matrix.shape

(3, 3)

In [24]:
#View number of elements (rows*columns)
matrix.size

9

In [25]:
#View number of dimensions
matrix.ndim

2

## Applying Operations to elements

In [26]:
# Create matrix
matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [27]:
#Create function that adds 100 to some number
add_100=lambda i: i +100

In [28]:
#Create vectorized function
vectorized_func=np.vectorize(add_100)

In [29]:
#apply function to all elements in matrix
vectorized_func(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [30]:
# broadcasting:Numpy arrays allow to perform operations if they are not the same
# Add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

## Finding Max and Min values

In [31]:
#Return maximum element
np.max(matrix)

9

In [32]:
# return minimum element
np.min(matrix)

1

## Calculating the Average,Variance and Standard Deviation

In [33]:
# Return mean
np.mean(matrix)

5.0

In [34]:
# Return variance
np.var(matrix)

6.666666666666667

In [35]:
# Return standard deviation
np.std(matrix)

2.581988897471611

In [40]:
#Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

## Reshaping Arrays

In [2]:
#Create 4x3 matrix
matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12]])

In [3]:
#Reshape matrix into 2x6matrix
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [4]:
#matrix reshape -1: means one row and as many columns as needed
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [5]:
#Reshape with one integer returns 1D array of that length
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Transposing a vector or matrix

In [6]:
#transpose matrix
matrix.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [7]:
#Transpose vector
np.array([1,2,3,4,5,6,7]).T

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
# Transpose row vector (notice second pair of brackets)
np.array([[1,2,3,4,5,6,7]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

## Flattening a Matrix

In [9]:
#Flatten matrix, simple method to transform a matrix into one-dimensional array
matrix.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
# alternative solution
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

## Finding the Rank of a Matrix

In [11]:
# create matrix
matrix=np.array([[1,1,1],
                [1,1,10],
                [1,1,15]])

In [13]:
#return matrix rank
np.linalg.matrix_rank(matrix)

2

## Calculating the determinant

In [14]:
#Return determinant of matrix
np.linalg.det(matrix)

0.0

## Getting the Diagonal of a Matrix

In [15]:
# Return diagonal elements
matrix.diagonal()

array([ 1,  1, 15])

In [16]:
#Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([ 1, 10])

In [17]:
#Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([1, 1])

## Calculating the trace of a matrix

In [3]:
# Creating a matrix
matrix=np.array([[1,2,3],
               [2,5,6],
               [8,9,7]])

In [4]:
# Return trace- sum of diagonal elements
matrix.trace()

13

In [5]:
#Return sum of diagonal elements
sum(matrix.diagonal())

13

## Finding Eigenvalues and Eigenvectors

In [7]:
#Explanation of eigenvalues and eigenvectors http://setosa.io/ev/eigenvectors-and-eigenvalues/
eigenvalues, eigenvectors=np.linalg.eig(matrix)

In [8]:
#View eigenvalues Explanation ofhttp://setosa.io/ev/eigenvectors-and-eigenvalues/
eigenvalues

array([15.22544832,  0.42178121, -2.64722953])

In [9]:
# View eigenvectors
eigenvectors

array([[-0.24566441, -0.51732532, -0.35634976],
       [-0.52586754,  0.75472505, -0.51729106],
       [-0.81431709, -0.40344096,  0.77809049]])

## Calculating Dot Products

In [11]:
#Create two vectors
vector_a=np.array([1,2,3])
vector_b=np.array([3,4,5])

In [12]:
#explanationd of Dot products: http://tutorial.math.lamar.edu/Classes/CalcII/DotProduct.aspx
#Calculate dot products
np.dot(vector_a,vector_b)

26

## Adding and subtracting matrices

In [17]:
#Create matrices
matrix_a=np.array([[1,2,3],
                  [2,3,5],
                  [1,2,1]])

In [18]:
matrix_b=np.array([[1,2,1],
                  [2,3,4],
                  [4,5,6]])

In [19]:
#Adding matrices
np.add(matrix_a,matrix_b)

array([[2, 4, 4],
       [4, 6, 9],
       [5, 7, 7]])

In [20]:
#Subtracting matrices
np.subtract(matrix_a,matrix_b)

array([[ 0,  0,  2],
       [ 0,  0,  1],
       [-3, -3, -5]])

In [21]:
#Alternative method to Add two matrices
matrix_a+matrix_b

array([[2, 4, 4],
       [4, 6, 9],
       [5, 7, 7]])

## Multiplying Matrices

In [6]:
#Create matrices
matrix_a=np.array([[1,3],
                  [2,4]])

In [7]:
matrix_b=np.array([[1,2],
                  [2,3]])

In [8]:
#Multiply two matrices
np.dot(matrix_a,matrix_b)

array([[ 7, 11],
       [10, 16]])

In [9]:
#Alternative way to multiply matrices
matrix_a @ matrix_b

array([[ 7, 11],
       [10, 16]])

In [10]:
# element-wide multiplication
matrix_a*matrix_b

array([[ 1,  6],
       [ 4, 12]])

## Inverting a Matrix

In [11]:
#create matrix
matrix=np.array([[1,5],
                [2,4]])

In [12]:
#calculate inverse of matrix
np.linalg.inv(matrix)

array([[-0.66666667,  0.83333333],
       [ 0.33333333, -0.16666667]])

In [13]:
# Multiply matrix and its inverse
matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

## Generating Random Values

In [14]:
# Set seed
np.random.seed(0)

In [16]:
# generate random floats between 0.0 and 1.0
np.random.random(3)

array([0.71518937, 0.60276338, 0.54488318])

In [19]:
# generate three random integers between 1 and 10
np.random.randint(1,3, 9)

array([2, 2, 1, 1, 2, 1, 1, 1, 1])

In [20]:
# Draw random numbers from a normal distribution with mean 0.0 and standard deviation 1.0
np.random.normal(0.0,1,3)

array([ 1.26611853, -0.50587654,  2.54520078])

In [21]:
# Draw random numbers from logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0,1,3)

array([ 2.52093742, -2.57088231, -2.34920103])

In [22]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0,2.0,3)

array([1.0202184 , 1.83261985, 1.77815675])